version: "3.5"

services:
  cardano-node:
    network_mode: host
    image: inputoutput/cardano-node:8.1.2
    environment:
      NETWORK: ${NETWORK}
      CARDANO_NODE_SOCKET_PATH: /ipc/node.socket
    volumes:
      - ./data/cardano-node/${NETWORK}/data:/data
      - ./data/cardano-node/${NETWORK}/node-ipc:/ipc
    ports:
      - 12798:12798
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  kupo:
    network_mode: host
    image: cardanosolutions/kupo:v2.7.0
    volumes:
      - ./data/kupo/${NETWORK}/db:/db
      - ./data/kupo/${NETWORK}/config:/config
      - ./data/cardano-node/${NETWORK}/node-ipc:/ipc
    command: 
      - "--node-socket"
      -  "/ipc/node.socket"
      -  "--node-config"
      -  "/config/config.json"
      -  "--since"
      -  "107144126.fc29b0f461e279c24c31817178507f3e1b00a6291a3b770671b30ef0592d12dd"
      -  "--match"
      -  "*"
      -  "--host"
      -  "0.0.0.0"
      -  "--workdir"
      -  "/db"
    ports:
      - 1442:1442
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  cardano-wallet:
    image: cardanofoundation/cardano-wallet:2023.7.18
    network_mode: host
    volumes:
      - ./data/wallet/${NETWORK}/wallet-db:/wallet-db
      - ./data/cardano-node/${NETWORK}/node-ipc:/ipc
    ports:
      - 8090:8090
    entrypoint: []
    command: > 
      bash -c "
        ([[ $$NETWORK == \"mainnet\" ]] && $$CMD --mainnet) ||
        ($$CMD --testnet /config/${NETWORK}/genesis-byron.json)
      "
    environment:
      CMD: "cardano-wallet serve --node-socket /ipc/node.socket --database /wallet-db --listen-address 0.0.0.0"
      NETWORK: preprod
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

